enum ActionTypes {
    START = '_START',
    SUCCESS = '_SUCCESS',
    FAIL = '_FAIL',
    INCREMENT = 'INCREMENT',
    DECREMENT = 'DECREMENT',
    ADD_TO_CART = 'ADD_TO_CART',
    REMOVE_FROM_CART = 'REMOVE_FROM_CART',
    CLEAR_THE_CART = 'CLEAR_THE_CART',
    ADD_REVIEW = 'ADD_REVIEW',
    FETCH_RESTAURANTS = 'FETCH_RESTAURANTS',
    FETCH_DISHES = 'FETCH_DISHES',
    FETCH_REVIEWS = 'FETCH_REVIEWS',
    FETCH_USERS = 'FETCH_USERS',
    SEND_ORDER = 'SEND_ORDER',
  }
  
  export default ActionTypes;   
